laravel/app/Models/CasoClinicoAvaliacao.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CasoClinicoAvaliacao extends Model
{
    protected $table = 'casos_clinicos_avaliacoes';

    protected $guarded = [];

    public function getNotaFormatadaAttribute()
    {
        return self::formataNota($this->nota);
    }

    public static function formataNota($nota)
    {
        return str_replace('.', ',', $nota + 0);
    }
}

laravel/app/Http/Controllers/Administracao/AdministracaoController.php
<?php

namespace App\Http\Controllers\Administracao;

use App\Http\Controllers\Controller;

class AdministracaoController extends Controller
{
    public function index()
    {
        return redirect()->route('administracao.coordenadores');
    }
}

laravel/app/Http/Controllers/Administracao/CasosClinicosController.php
<?php

namespace App\Http\Controllers\Administracao;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Notification;
use Carbon\Carbon;

use App\Models\Avaliador;
use App\Models\CasoClinico;
use App\Notifications\CasoDistribuido;

class CasosClinicosController extends Controller
{
    protected $avaliadores;

    public function __construct()
    {
        $this->avaliadores = Avaliador::get();
    }

    public function index(Request $request)
    {
        $casosClinicos = CasoClinico::with('medico', 'avaliacoes')
            ->withCount('avaliacoes')
            ->validado();

        if ($request->filtro === 'sem_avaliacoes') {
            $casosClinicos = $casosClinicos->doesntHave('avaliacoes');
        } else if ($request->filtro === 'avaliados') {
            $casosClinicos = $casosClinicos->has('avaliacoes');
        }

        if ($request->distribuido === 'sim') {
            $casosClinicos = $casosClinicos->whereNotNull('distribuido_em');
        } else if ($request->distribuido === 'nao') {
            $casosClinicos = $casosClinicos->whereNull('distribuido_em');
        }

        if ($termo = $request->busca) {
            $casosClinicos = $casosClinicos->whereHas('medico', function($query) use ($termo) {
                $query
                    ->where('nome', 'LIKE', "%$termo%")
                    ->orWhere('email', 'LIKE', "%$termo%");
            });
        }

        return view('administracao.casos-clinicos.index', [
            'avaliadoresCount' => $this->avaliadores->count(),
            'casosClinicos'    => $casosClinicos->get()->map(function($casoClinico) {
                return $this->spreadAvaliacoes($casoClinico);
            })
        ]);
    }

    public function show($id)
    {
        $casoClinico = CasoClinico::validado()->findOrFail($id);

        if ($casoClinico->distribuido_em) {
            return view('administracao.casos-clinicos.show', [
                'casoClinico' => $this->spreadAvaliacoes($casoClinico)
            ]);
        }

        return view('administracao.casos-clinicos.edit', compact('casoClinico'));
    }

    public function post(Request $request, $id)
    {
        $casoClinico = CasoClinico::paraDistribuir()->findOrFail($id);

        $this->validateCaso($request);

        try {
            $this->saveCaso($casoClinico, $request);

            return back()->with('success', 'Caso clínico salvo com sucesso!');
        } catch (\Exception $e) {
            return back()
                ->withInput()
                ->withErrors(['Ocorreu um erro ao salvar o caso clínico.']);
        }
    }

    public function distribuir(Request $request, $id)
    {
        $casoClinico = CasoClinico::paraDistribuir()->findOrFail($id);

        $this->validateCaso($request);

        try {
            $this->saveCaso($casoClinico, $request, true);

            return redirect()
                ->route('administracao.casos-clinicos')
                ->with('success', 'Caso clínico distribuído com sucesso!');
        } catch (\Exception $e) {
            return back()
                ->withInput()
                ->withErrors(['Ocorreu um erro ao distribuir o caso clínico.']);
        }
    }

    protected function spreadAvaliacoes(CasoClinico $casoClinico)
    {
        $casoClinico->avaliacoes = $this->avaliadores->map(function($avaliador) use ($casoClinico) {
            return $casoClinico->avaliacoes->first(function($avaliacao) use ($avaliador) {
                return $avaliacao->avaliador_id === $avaliador->id;
            });
        });

        return $casoClinico;
    }

    protected function validateCaso(Request $request)
    {
        $request->validate([
            'nome'                       => 'required',
            'crm'                        => 'required',
            'telefone'                   => 'required',
            'participantes'              => 'required|array',
            'titulo'                     => 'required',
            'relato'                     => 'required',
            'conclusao'                  => 'required',
            'referencias_bibliograficas' => 'required'
        ]);
    }

    protected function saveCaso($casoClinico, Request $request, $distribuir = false)
    {
        $administrador   = auth('administracao')->user();
        $casoClinicoCopy = $casoClinico->replicate();

        $medico = $casoClinico->medico;
        $medico->update([
            'nome'     => $request->nome,
            'crm'      => $request->crm,
            'telefone' => $request->telefone,
        ]);

        $casoClinico->update([
            'participantes'              => $request->participantes,
            'titulo'                     => $request->titulo,
            'relato'                     => $request->relato,
            'conclusao'                  => $request->conclusao,
            'referencias_bibliograficas' => $request->referencias_bibliograficas,
            'distribuido_em'             => $distribuir ? Carbon::now() : null,
            'distribuido_por'            => $distribuir ? $administrador->id : null,
        ]);

        /**
         * Verifica alterações nos dados do caso clínico / médico
         * Se houverem mudanças grava a data e id do administrador
         * em um json na coluna "alteracoes_administracao"
         */

        $casoClinicoChanges = array_filter($casoClinico->getChanges(), function ($key) {
            return !in_array($key, ['participantes', 'updated_at']);
        }, ARRAY_FILTER_USE_KEY);

        $previousParticipantes = json_decode($casoClinicoCopy->getAttributes()['participantes'], true);
        $participantesChanges  = array_filter($request->participantes, function($participante, $index) use ($previousParticipantes) {
            return
                $participante['nome'] !== $previousParticipantes[$index]['nome'] ||
                $participante['crm'] !== $previousParticipantes[$index]['crm'];
        }, ARRAY_FILTER_USE_BOTH);

        if (count($casoClinicoChanges) || count($participantesChanges) || count($medico->getChanges())) {
            $alteracoes   = json_decode($casoClinico->alteracoes_administracao, true) ?: [];
            $alteracoes[] = [
                'administrador_id' => $administrador->id,
                'data_alteracao'   => Carbon::now()
            ];

            $casoClinico->update(['alteracoes_administracao' => json_encode($alteracoes)]);
        }

        if ($distribuir) {
            Notification::send(
                Avaliador::all(),
                new CasoDistribuido($casoClinico)
            );
        }
    }
}

laravel/app/Http/Controllers/Administracao/ConfiguracoesController.php
<?php

namespace App\Http\Controllers\Administracao;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

use App\Models\Grupo;
use App\Models\Avaliador;
use App\Models\Farmacovigilante;
use App\Models\Administrador;

class ConfiguracoesController extends Controller
{
    public function index()
    {
        return view('administracao.configuracoes.index', [
            'grupos'            => Grupo::all(),
            'avaliadores'       => Avaliador::all(),
            'farmacovigilantes' => Farmacovigilante::all(),
            'administradores'   => Administrador::all(),
        ]);
    }


    private function createOrUpdate($input, $class) {
        $data = [];

        if (!is_array($input)) {
            return;
        }

        foreach(array_keys($input) as $fieldKey) {
            foreach($input[$fieldKey] as $key => $value) {
                $data[$key][$fieldKey] = $value;
            }
        }

        foreach($data as $key => $obj) {
            $newObj = array_merge(
                array_diff_assoc($obj, ['id' => $obj['id']]),
                in_array($class, [Farmacovigilante::class, Administrador:: class])
                    ? ['password' => Hash::make(Str::random(32))]
                    : []
            );

            $obj['id'] === 'create'
                ? $class::create($newObj)
                : $class::findOrFail($obj['id'])->update($obj);
        }
    }

    public function post(Request $request)
    {
        try {
            $this->createOrUpdate($request->grupo, Grupo::class);
            $this->createOrUpdate($request->avaliador, Avaliador::class);
            $this->createOrUpdate($request->farmacovigilante, Farmacovigilante::class);
            $this->createOrUpdate($request->administrador, Administrador::class);

            return back()->with('success', 'Dados atualizados com sucesso!');
        } catch (\Exception $e) {
            return back()->withErrors(['Ocorreu um erro ao atualizar os dados.']);
        }
    }

    public function delete(Request $request)
    {
        try {
            if ($request->tipo === 'farmacovigilante') {
                $obj = Farmacovigilante::findOrFail($request->id);
            } else if ($request->tipo === 'administrador') {
                $obj = Administrador::findOrFail($request->id);
            }

            if (!$obj || ($request->tipo === 'administrador' && $obj->id === auth('administracao')->user()->id)) {
                abort('500');
            }

            $obj->delete();

            return back()->with('success', 'Usuário excluído com sucesso!');
        } catch (\Exception $e) {
            return back()->withErrors(['Ocorreu um erro ao excluir o usuário.']);
        }
    }
}

laravel/app/Http/Controllers/Administracao/CoordenadoresController.php
<?php

namespace App\Http\Controllers\Administracao;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Carbon\Carbon;

use App\Models\Grupo;
use App\Models\Medico;
use App\Models\TextoConvite;
use App\Notifications\ConviteMedico;

class CoordenadoresController extends Controller
{
    public function index(Request $request)
    {
        if ($request->busca) {
            return view('administracao.coordenadores.busca', [
                'medicos' => Medico::busca($request->busca)->get()
            ]);
        }

        return view('administracao.coordenadores.index', [
            'grupos' => Grupo::all()
        ]);
    }

    public function grupo(Request $request, $id)
    {
        $grupo = Grupo::findOrFail($id);

        return view('administracao.coordenadores.grupo', [
            'grupo'   => $grupo,
            'medicos' => $request->busca
                ? $grupo->medicos()->busca($request->busca)->get()
                : $grupo->medicos
        ]);
    }

    public function grupoPost(Request $request, $id)
    {
        $grupo = Grupo::findOrFail($id);

        $request->validate([
            'nome' => 'required',
            'email' => 'required|email|unique:medicos,email',
        ]);

        try {
            $grupo->medicos()->create([
                'nome'          => $request->nome,
                'email'         => $request->email,
                'password'      => Hash::make(Str::random(32)),
                'token_convite' => Str::random(32)
            ]);

            return back()->with('success', 'Coordenador cadastrado com sucesso!');
        } catch (\Exception $e) {
            return back()->withErrors(['Ocorreu um erro ao cadastrar o coordenador.']);
        }
    }

    public function grupoDelete($grupoId, $medicoId)
    {
        try {
            $grupo  = Grupo::findOrFail($grupoId);
            $medico = Medico::where('grupo_id', $grupo->id)->findOrFail($medicoId);

            if ($medico->casoClinico && $medico->casoClinico->enviado_em) {
                return back()->withErrors(['Não é possível excluir um coordenador que já enviou um caso clínico']);
            }

            $medico->delete();

            return back()->with('success', 'Coordenador excluído com sucesso!');
        } catch (\Exception $e) {
            return back()->withErrors(['Ocorreu um erro ao excluir o coordenador.']);
        }
    }

    public function grupoConvite($grupoId, $medicoId)
    {
        try {
            $grupo  = Grupo::findOrFail($grupoId);
            $medico = Medico::where('grupo_id', $grupo->id)->findOrFail($medicoId);
            $field  = $medico->convite_enviado_em ? 'convite_reenviado_em': 'convite_enviado_em';

            if ($medico->cadastrado_em) {
                return back()->withErrors(['Médico já está cadastrado.']);
            }

            if (!$grupo->data_limite) {
                return back()->withErrors(['Cadastre a data limite do grupo antes de enviar convites.']);
            }

            $medico->update([
                $field          =>  Carbon::now(),
                'token_convite' => Str::random(32)
            ]);
            $medico->notify(new ConviteMedico($medico));

            return back()->with('success', 'Convite enviado com sucesso!');
        } catch (\Exception $e) {
            return back()->withErrors(['Ocorreu um erro ao enviar o convite.']);
        }

    }

    public function textoConvite()
    {
        return view('administracao.coordenadores.texto-convite', [
            'textoConvite' => TextoConvite::first()
        ]);
    }

    public function textoConvitePost(Request $request)
    {
        $request->validate([
            'texto' => 'required'
        ]);

        try {
            $texto = TextoConvite::firstOrFail();
            $texto->update([
                'texto' => $request->texto
            ]);

            return back()->with('success', 'Texto salvo com sucesso!');
        } catch (\Exception $e) {
            return back()->withErrors(['Ocorreu um erro ao salvar o texto.']);
        }
    }
}

laravel/app/Http/Controllers/Administracao/ResultadosController.php
<?php

namespace App\Http\Controllers\Administracao;

use App\Http\Controllers\Controller;

use App\Models\CasoClinico;

class ResultadosController extends Controller
{
    public function index()
    {
        return view('administracao.resultados.index', [
            'resultados' => CasoClinico::resultadosOrdenados(3)
        ]);
    }
}

laravel/app/Http/Controllers/Avaliador/CasosClinicosController.php
<?php

namespace App\Http\Controllers\Avaliador;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Models\CasoClinico;

class CasosClinicosController extends Controller
{
    public function index($id = null)
    {
        $avaliador = auth('avaliador')->user();

        if ($id) {
            return view('avaliador.casos-clinicos.edit', [
                'casoClinico' => CasoClinico::paraAvaliar($avaliador->id)->findOrFail($id)
            ]);
        }

        return view('avaliador.casos-clinicos.index', [
            'casosClinicos' => CasoClinico::paraAvaliar($avaliador->id)->get()
        ]);
    }

    public function post(Request $request, $id)
    {
        $avaliador   = auth('avaliador')->user();
        $casoClinico = CasoClinico::paraAvaliar($avaliador->id)->findOrFail($id);

        $request->merge(['nota' => str_replace(',', '.', $request->nota)]);
        $request->validate(['nota' => 'required|numeric|between:0,10']);

        try {
            $casoClinico->avaliacoes()->create([
                'caso_id'      => $casoClinico->id,
                'avaliador_id' => $avaliador->id,
                'nota'         => $request->nota,
            ]);

            return redirect()
                ->route('avaliador.casos-clinicos')
                ->with('success', 'Caso clínico avaliado com sucesso!');
        } catch (\Exception $e) {
            return back()
                ->withInput()
                ->withErrors(['Ocorreu um erro ao avaliar o caso clínico.']);
        }
    }
}

laravel/resources/views/administracao/casos-clinicos/_filtros.blade.php
<div class="filtros">
    <div class="col">
        <span>Notas recebidas:</span>
        <select name="filtro" class="select-filter">
            <option value="null" data-route="{{ route('administracao.casos-clinicos', array_merge($_GET, ['filtro' => ''])) }}" @if(!request('filtro')) selected @endif>Selecione...</option>
            <option value="sem_avaliacoes" data-route="{{ route('administracao.casos-clinicos', array_merge($_GET, ['filtro' => 'sem_avaliacoes'])) }}" @if(request('filtro') === 'sem_avaliacoes') selected @endif>Sem nenhuma avaliação</option>
            <option value="avaliados" data-route="{{ route('administracao.casos-clinicos', array_merge($_GET, ['filtro' => 'avaliados'])) }}" @if(request('filtro') === 'avaliados') selected @endif>Avaliados</option>
        </select>
    </div>
    <div class="col">
        <span>Enviado para Avaliação:</span>
        <select name="distribuido" class="select-filter small">
            <option value="null" data-route="{{ route('administracao.casos-clinicos', array_merge($_GET, ['distribuido' => ''])) }}" @if(!request('distribuido')) selected @endif>Selecione...</option>
            <option value="sim" data-route="{{ route('administracao.casos-clinicos', array_merge($_GET, ['distribuido' => 'sim'])) }}" @if(request('distribuido') === 'sim') selected @endif>Sim</option>
            <option value="nao" data-route="{{ route('administracao.casos-clinicos', array_merge($_GET, ['distribuido' => 'nao'])) }}" @if(request('distribuido') === 'nao') selected @endif>Não</option>
        </select>
    </div>
    <div class="col">
        <span>Buscar por:</span>
        <form action="{{ route('administracao.casos-clinicos') }}" method="GET">
            @foreach($_GET as $key => $value)
                @if($key !== 'busca')
                    <input type="hidden" name="{{ $key }}" value="{{ $value }}">
                @endif
            @endforeach
            <div class="input-busca">
                <input type="text" name="busca" placeholder="Nome do Médico Coordenador ou e-mail" value="{{ request('busca') }}">
                <input type="submit">
            </div>
        </form>
    </div>
</div>

laravel/resources/views/administracao/casos-clinicos/edit.blade.php
@extends('administracao.common.template')

@section('content')

    <div class="main-padding administracao-casos-clinicos">
        <div class="center">
            <h1>CASO CLÍNICO &middot; ENVIAR PARA AVALIAR</h1>

            <form action="{{ route('administracao.casos-clinicos.post', $casoClinico->id) }}" method="POST" class="form-caso">
                @csrf

                @include('common.flash')

                <div class="grupo">
                    <h3>IDENTIFICAÇÃO DO GRUPO</h3>

                    <div class="grid">
                        <div class="col">
                            <p>Médico(a) Coordenador(a)</p>
                            <div class="input">
                                <label>nome</label>
                                <input type="text" name="nome" value="{{ old('nome') ?: $casoClinico->medico->nome }}">
                            </div>
                            <div class="input">
                                <label>CRM</label>
                                <input type="text" name="crm" value="{{ old('crm') ?: $casoClinico->medico->crm }}">
                            </div>
                            <div class="input">
                                <label>e-mail</label>
                                <input type="text" name="email" value="{{ $casoClinico->medico->email }}" readonly>
                            </div>
                            <div class="input">
                                <label>telefone</label>
                                <input type="text" name="telefone" value="{{ old('telefone') ?: $casoClinico->medico->telefone }}">
                            </div>
                        </div>
                        <div class="col">
                            <p>Médicos(as) participantes</p>
                            @foreach(range(0, 4) as $i)
                                <div class="row">
                                    <div class="input">
                                        <label>nome</label>
                                        <input type="text" name="participantes[{{ $i }}][nome]" value="{{ old("participantes.$i.nome") ?: ($casoClinico && array_key_exists($i, $casoClinico->participantes) ? $casoClinico->participantes[$i]->nome : '') }}">
                                    </div>
                                    <div class="input">
                                        <div class="input">
                                            <label>CRM</label>
                                            <input type="text" name="participantes[{{ $i }}][crm]" value="{{ old("participantes.$i.crm") ?: ($casoClinico && array_key_exists($i, $casoClinico->participantes) ? $casoClinico->participantes[$i]->crm : '') }}">
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>

                <h2>CONTEÚDO DO CASO CLÍNICO</h2>

                <div class="row-caso">
                    <label>título do caso clínico</label>
                    <input type="text" name="titulo" value="{{ old('titulo') ?: ($casoClinico ? $casoClinico->titulo : '') }}">
                </div>
                <div class="row-caso">
                    <label>relato do caso clínico</label>
                    <textarea name="relato" class="text-editor text-editor-caso text-editor-caso-grande">{!! old('relato') ?: ($casoClinico ? $casoClinico->relato : '') !!}</textarea>
                </div>
                <div class="row-caso">
                    <label>conclusão</label>
                    <textarea name="conclusao" class="text-editor text-editor-caso">{!! old('conclusao') ?: ($casoClinico ? $casoClinico->conclusao : '') !!}</textarea>
                </div>
                <div class="row-caso">
                    <label>referências bibliográficas</label>
                    <textarea name="referencias_bibliograficas" class="text-editor text-editor-caso">{!! old('referencias_bibliograficas') ?: ($casoClinico ? $casoClinico->referencias_bibliograficas : '') !!}</textarea>
                </div>

                <div class="btn-group">
                    <input type="submit" value="SALVAR ALTERAÇÕES" class="btn btn-administracao">
                    <input type="submit" value="DISTRIBUIR PARA AVALIADORES" class="btn btn-administracao btn-enviar-confirmacao" data-confirmacao="Deseja distribuir o caso clínico para avaliadores? Essa ação não pode ser desfeita." formaction="{{ route('administracao.casos-clinicos.distribuir', $casoClinico->id) }}">
                </div>
            </form>
        </div>
    </div>

@endsection

laravel/resources/views/administracao/casos-clinicos/index.blade.php
@extends('administracao.common.template')

@section('content')

    <div class="main-padding administracao-casos-clinicos">
        <div class="center">
            @include('common.flash')

            @include('administracao.casos-clinicos._filtros')

            @if(count($casosClinicos))
                <div class="casos-lista" style="--avaliadores: {{ $avaliadoresCount }}">
                    <div class="grid">
                        <span><br>CASO CLÍNICO / MÉDICO:</span>
                        <span>DATA DE<br>RECEBIM.:</span>
                        <span>ENVIO P/<br>AVALIAÇÃO:</span>
                        <span style="grid-column: span 2"><br>AVALIADO:</span>
                    </div>

                    @foreach($casosClinicos as $casoClinico)
                        <div class="grid @if(!$casoClinico->distribuido_em) grid-border @endif">
                            <div class="cell cell-titulo">
                                {{ $casoClinico->titulo }}<br>
                                Dr.(a) {{ $casoClinico->medico->nome }}
                            </div>
                            <div class="cell cell-data">
                                {!! $casoClinico->enviado_em->format('d/m/y \\<\\b\\r\\> H:i') !!}
                            </div>
                            <div class="cell cell-data">
                                {!! $casoClinico->distribuido_em
                                    ? $casoClinico->distribuido_em->format('d/m/y \\<\\b\\r\\> H:i')
                                    : '-'
                                !!}
                            </div>
                            @foreach($casoClinico->avaliacoes as $avaliacao)
                                <div class="cell cell-avaliacao">
                                    @if(!$avaliacao)
                                        <span style="color: #FC1C1C">X</span>
                                    @else
                                        <span>{{ $avaliacao->nota_formatada }}</span>
                                    @endif
                                </div>
                            @endforeach
                            <a href="{{ route('administracao.casos-clinicos.show', $casoClinico->id) }}" class="btn-caso">
                                {{ $casoClinico->distribuido_em ? 'VER' : 'ENVIAR PARA AVALIAR' }}
                            </a>
                        </div>
                    @endforeach
                </div>
            @else
                <div class="nenhum">Nenhum caso clínico encontrado.</div>
            @endif
        </div>
    </div>

@endsection

laravel/resources/views/administracao/casos-clinicos/show.blade.php
@extends('administracao.common.template')

@section('content')

    <div class="main-padding administracao-casos-clinicos">
        <div class="center">
            <h1>CASO CLÍNICO &middot; VISUALIZAR DETALHES</h1>

            <div class="form-caso">
                <div class="grupo">
                    <h3>IDENTIFICAÇÃO DO GRUPO</h3>

                    <div class="grid">
                        <div class="col">
                            <p>Médico(a) Coordenador(a)</p>
                            <div class="input">
                                <label>nome</label>
                                <input type="text" name="nome" value="{{ $casoClinico->medico->nome }}" readonly>
                            </div>
                            <div class="input">
                                <label>CRM</label>
                                <input type="text" name="crm" value="{{ $casoClinico->medico->crm }}" readonly>
                            </div>
                            <div class="input">
                                <label>e-mail</label>
                                <input type="text" name="email" value="{{ $casoClinico->medico->email }}" readonly>
                            </div>
                            <div class="input">
                                <label>telefone</label>
                                <input type="text" name="telefone" value="{{ $casoClinico->medico->telefone }}" readonly>
                            </div>
                        </div>
                        <div class="col">
                            <p>Médicos(as) participantes</p>
                            @foreach(range(0, 4) as $i)
                                <div class="row">
                                    <div class="input">
                                        <label>nome</label>
                                        <input type="text" name="participantes[{{ $i }}][nome]" value="{{ $casoClinico && array_key_exists($i, $casoClinico->participantes) ? $casoClinico->participantes[$i]->nome : '' }}" readonly>
                                    </div>
                                    <div class="input">
                                        <div class="input">
                                            <label>CRM</label>
                                            <input type="text" name="participantes[{{ $i }}][crm]" value="{{ $casoClinico && array_key_exists($i, $casoClinico->participantes) ? $casoClinico->participantes[$i]->crm : '' }}" readonly>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>

                <div class="row-caso">
                    <label>título do caso clínico</label>
                    <div class="text-editor-readonly">
                        <p>{{ $casoClinico->titulo }}</p>
                    </div>
                </div>
                <div class="row-caso">
                    <label>relato do caso clínico</label>
                    <div class="text-editor-readonly">{!! $casoClinico->relato !!}</div>
                </div>
                <div class="row-caso">
                    <label>conclusão</label>
                    <div class="text-editor-readonly">{!! $casoClinico->conclusao !!}</div>
                </div>
                <div class="row-caso">
                    <label>referências bibliográficas</label>
                    <div class="text-editor-readonly">{!! $casoClinico->referencias_bibliograficas !!}</div>
                </div>

                <div class="status-avaliadores">
                    <div class="distribuido-em">
                        ENVIADO PARA AVALIADORES EM:
                        <span>{{ $casoClinico->distribuido_em->format('d/m/y - H:i') }}</span>
                    </div>
                    <div class="grid" style="--rows: {{ ceil(count($casoClinico->avaliacoes) / 2) }}">
                        @foreach($casoClinico->avaliacoes as $key => $avaliacao)
                            <div @if(!$avaliacao) class="highlight" @endif>
                                <span>AVALIADOR {{ $key + 1 }}</span>
                                <span>
                                    @if(!$avaliacao)
                                        <strong>NOTA NÃO APLICADA</strong>
                                    @else
                                        AVALIADO EM
                                        {{ $avaliacao->created_at->format('d/m/y - H:i') }}
                                    @endif
                                </span>
                            </div>
                        @endforeach
                    </div>
                </div>

                <div class="btn-group">
                    <a href="{{ route('administracao.casos-clinicos') }}" class="btn btn-administracao">VOLTAR</a>
                </div>
            </div>
        </div>
    </div>

@endsection